spring:
  datasource:
    url: jdbc:h2:mem:db_transaction
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: ${SECURE_KEY_USERNAME}
      password: ${SECURE_KEY_PASSWORD}
